<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="PA1_template_files/bootstrap-2.3.2/css/bootstrap.min.css" rel="stylesheet" />
<link href="PA1_template_files/bootstrap-2.3.2/css/bootstrap-responsive.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-2.3.2/js/bootstrap.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PA1_template_files/highlight/default.css"
      type="text/css" />
<script src="PA1_template_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Reproducible Research: Peer Assessment 1</h1>
</div>


<p>Setting up Global knitr options</p>
<pre class="r"><code>library(knitr)
opts_chunk$set(echo = TRUE)</code></pre>
<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<pre class="r"><code>activity &lt;- read.csv(&quot;activity.csv&quot;, header = TRUE)</code></pre>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is mean total number of steps taken per day?</h2>
<p>Find the total number of steps taken per day</p>
<pre class="r"><code>TotalStepsPerDay &lt;- tapply(activity$steps, activity$date, FUN = sum)</code></pre>
<p>Plot histogram of the total number of steps taken per day</p>
<pre class="r"><code>hist(TotalStepsPerDay, breaks = 6, main = &quot;Total number of steps per day&quot;,
     xlab = &quot;Steps per day&quot;, ylab = &quot;Frequency&quot;, col = &quot;blue&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-4-1.png" /></p>
<p>Compute the mean and median total number of steps per day</p>
<pre class="r"><code>mean(TotalStepsPerDay, na.rm = TRUE)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code>median(TotalStepsPerDay, na.rm = TRUE)</code></pre>
<pre><code>## [1] 10765</code></pre>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<p>Find the average number of steps taken per 5-minute interval</p>
<pre class="r"><code>MeanStepsPerInterval &lt;- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)</code></pre>
<p>Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)</p>
<pre class="r"><code>plot(MeanStepsPerInterval, type = &quot;l&quot;, main = (&quot;The average daily activity pattern&quot;), 
    ylab = &quot;Number of steps&quot;, xlab = &quot;Interval&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-7-1.png" /></p>
<p>Find the 5-minute interval which, on average across all the days in the dataset, contains the maximum number of steps?</p>
<pre class="r"><code>maxInterval &lt;- which.max(MeanStepsPerInterval)
names(maxInterval)</code></pre>
<pre><code>## [1] &quot;835&quot;</code></pre>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<p>Find the total number of missing values in the dataset</p>
<pre class="r"><code>sum(as.numeric(is.na(activity$steps)))</code></pre>
<pre><code>## [1] 2304</code></pre>
<ul>
<li><p>Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.</p></li>
<li><p>Create a new dataset that is equal to the original dataset but with the missing data filled in.</p></li>
<li><p>Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?</p></li>
</ul>
<pre class="r"><code>MeanStepsPerInterval_vec &lt;- as.vector(MeanStepsPerInterval)
MeanStepsPerInterval_vec &lt;- rep(MeanStepsPerInterval_vec, 61)
MeanStepsPerInterval_vec[!is.na(activity$steps)] = 1

stepsData_vec &lt;- as.vector(activity$steps)
stepsData_vec[is.na(stepsData_vec)] = 1

activity_NoMissData &lt;- activity
activity_NoMissData$steps &lt;- MeanStepsPerInterval_vec * stepsData_vec
TotalStepsPerDay_NoMissData &lt;- tapply(activity_NoMissData$steps, activity_NoMissData$date, 
    sum)
hist(TotalStepsPerDay_NoMissData, breaks = 6, main = &quot;Total number of steps per day&quot;, 
    xlab = &quot;Steps per day&quot;, ylab = &quot;Frequency&quot;, col = &quot;blue&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-10-1.png" /></p>
<p>Find the mean and median total number of steps taken per day.</p>
<pre class="r"><code>mean(TotalStepsPerDay_NoMissData)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code>median(TotalStepsPerDay_NoMissData)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<p>The imputation has a slight impact on the median total number of steps taken per day. It was changed from 10765 to 10766.19</p>
<p>The mean total number of steps taken per day remained the same.</p>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
<ul>
<li>Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.</li>
</ul>
<pre class="r"><code># Create a factor variable with two levels (weekday, weekend)
temp &lt;- as.POSIXlt(activity$date, format = &quot;%Y-%m-%d&quot;)
WeekDay &lt;- temp$wday
WeekDay[WeekDay == 0] = 0
WeekDay[WeekDay == 6] = 0
WeekDay[WeekDay != 0] = 1
WeekDays_Factor &lt;- factor(WeekDay, levels = c(0, 1))
activity$WD &lt;- WeekDays_Factor

#Calculate the mean
MeanStepsPerWeekday &lt;- tapply(activity$steps, list(activity$interval, activity$WD), mean, 
    na.rm = T)</code></pre>
<ul>
<li>Make a panel plot containing a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.</li>
</ul>
<pre class="r"><code>par(mfrow = c(2, 1))
# Display the two plots
with(activity, {
    par(mai = c(0, 1, 0.8, 0))
    plot(MeanStepsPerWeekday[, 1], type = &quot;l&quot;, main = &quot;Activity patterns on weekends and weekdays&quot;, 
        xaxt = &quot;n&quot;, ylab = &quot;Weekends&quot;)
    
    par(mai = c(0.8, 1, 0, 0))
    plot(MeanStepsPerWeekday[, 2], type = &quot;l&quot;, xlab = &quot;Interval&quot;, ylab = &quot;Weekdays&quot;)

})</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-13-1.png" /></p>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
